./local/run/run_input_stat.sh LIESTdev02 est spanish
./local/run/run_input_stat.sh LIESTdev02 est thai
./local/run/run_input_stat.sh LIESTdev02 est male
./local/run/run_input_stat.sh LIESTdev02 est young
./local/run/run_input_stat.sh LIESTdev02 est grade_A
./local/run/run_input_stat.sh LIESTdev02 est grade_B2
./local/run/run_input_stat.sh LIESTdev02 est grade_C
./local/run/run_input_stat.sh LIESTcal01 est spanish
./local/run/run_input_stat.sh LIESTcal01 est thai
./local/run/run_input_stat.sh LIESTcal01 est male
./local/run/run_input_stat.sh LIESTcal01 est young
./local/run/run_input_stat.sh LIESTcal01 est grade_A
./local/run/run_input_stat.sh LIESTcal01 est grade_B2
./local/run/run_input_stat.sh LIESTcal01 est grade_C
